[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/AFAC-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
sleepApplication = true
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/actuator/health/liveness"
interval = "15s"
timeout = "10s"
retries = 3
startPeriod = "30s"

[service]
internal_port = 8081
port = 8081

[variables]
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
SPRING_DATASOURCE_USERNAME = "${PGUSER}"
SPRING_DATASOURCE_PASSWORD = "${PGPASSWORD}" 