[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
sleepApplication = false
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/actuator/health/liveness"
interval = "30s"
timeout = "10s"
retries = 5
startPeriod = "60s"

[service]
internal_port = 8081
port = 8081

[env]
RAILWAY_ENVIRONMENT = "production"

[[plugins]]
name = "postgresql"
auto_apply = true

[variables]
PORT = "8081"
SPRING_PROFILES_ACTIVE = "prod" 