[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
sleepApplication = true
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/actuator/health/liveness"
interval = "15s"
timeout = "10s"
retries = 3
startPeriod = "30s"

[service]
internal_port = 8081
port = 8081

[variables]
PORT = "8081"
SPRING_PROFILES_ACTIVE = "prod" 