[build]
cmd = "./mvnw clean package -DskipTests && ls -la target/"
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/AFAC-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 180
healthcheckInterval = 15
restartPolicyType = "on_failure"
sleepApplication = true
sleepMode = "idle"
idleTimeout = "1h"

[service]
internal_port = 8081
port = 8081

[variables]
SPRING_PROFILES_ACTIVE = "prod" 